language: cpp

os: 
  -linux
dist: bionic

compiler:
    -clang++
    -gcc

install:
    -cmake

script:
- sh ./scripts/build_linux.sh

notification:
    email: true
    on_success: always
    on_failure: always
    on_start: always
