language: cpp

compiler:
    -clang
    -gcc

os: 
  -linux

install:
    -cmake

branches:
    only:
        -main

notification:
    email: true
    on_success: always
    on_failure: always
    on_start: always